comment = "Write a meaningful comment about the experiment."

[train]
model_path = test_1

# whether to load pretrained mode
preload_model = False

# pretrained model path
pretrain_model_path = "trained_models/test_1.pth"

# number of epochs to train
num_epochs = 100

# batch size for training
batch_size = 5

# Optimizer
optim = adam

# Learning rate
lr = 0.0001

# weight decay
weight_decay = 0.0


# feature size
feature_H = 512
feature_W = 64

# using gpu?
use_gpu = False